#! ksh
#! @revision 2021-08-23 (Mon) 15:25:11

function tomcat_envs {
    typeset dir=${rc.prog.topdir} file
    integer cols=$(tput cols)-63

    typeset pass prevpass files links

    printf '                                 \E[1;35mENVIRONMENTS\E[0m\n'
    for pass in 1 2; do for file in $dir/.env*; do
        (( prevpass == 1 && pass == 2 )) && printf '\n                                 \E[1;35mALIASES\E[0m\n'
        typeset env=${file##*/}; [[ $env == .env ]] && env='(default)' || env=${env#*-}
        typeset brief=$(sed -n '/^#! @brief/{s/^#! @brief[ ]*//;p;}' $file)
        typeset revision=$(sed -n '/^#! @revision/{s/^#! @revision[ ]*//;p;}' $file)
        typeset symlink=; [[ -L $file ]] && symlink=$(readlink $file | sed 's,.*\.env-,,')
        if (( pass == 1 )) && [[ -z $symlink ]]
        then printf "\E[32m%30s\E[0;2m =\E[0m %-${cols}s\E[0;2m %s\E[0m\n" $env "$brief" "$revision"
        elif (( pass == 2 )) && [[ -n $symlink ]]
        then printf "\E[2;35m%14s\E[0;2m →\E[0;32m%14s\E[0;2m =\E[0m %-${cols}s\E[0;2m %s\E[0m\n" \
             $symlink $env "$brief" "$revision"; fi
        prevpass=$pass
    done; done


}

# __END__
