#! ksh

function tomcat_logfiles {

    # Determine location of our Tomcat server's log files
    typeset dir=$PWD; [[ ${rc.tomcat.clog} == */* ]] && dir=${rc.tomcat.clog%/*}

    typeset logfile; for logfile in $dir/*.{log,out}; do

        # Ignore files matching /\.\d{4}-\d{2}-\d2}\./ and /-\d{8}-\d{4}/
        [[ $logfile == *.[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].*                    ]] && continue
        [[ $logfile == *-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9].* ]] && continue

        print $logfile

    done

}

# __END__
